config/routes.rb
Rails.application.routes.draw do

  resources :favorites

  devise_for :users
  root 'restaurants#index'

  post '/restaurants/:id', to: 'restaurants#show'
  get 'user_details' => 'restaurants#user'  

  controller :comments do
	post 'comment' => :create
  end

  resources :restaurants
  resources :comments
  resources :votes

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :restaurant

  def self.get_user_comments(user_param)
    Comment.joins('LEFT OUTER JOIN restaurants ON restaurants.id = comments.restaurantID').where('comments.user = ?', user_param)
  end

  def self.get_comment_restaurant_name(restaurant)
    Restaurant.where(:id => restaurant).first
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  def self.is_favorite(user, restaurant)
    c = Favorite.where(:user => user, :restaurantID => restaurant).count
    if c > 0
	return true
    else return false
    end
  end

  def self.get_user_favorites(user_param)
    Restaurant.joins('LEFT OUTER JOIN favorites ON restaurants.id = favorites.restaurantID').where('favorites.user = ?', user_param)
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :comments do
	def get_comments(restaurantID)
		Comment.where(:restaurantID => restaurantID)
  	end
  end
  has_many :votes
  searchkick autocomplete: ['name']  

  validates :name, :uniqueness => {:scope => [:address1, :zip], message: 'The restaurant at this address has already been created.'}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :restaurant

def self.count_up_votes(restaurant)
  Vote.where(:restaurantID => restaurant, :split => 't').count
end 

def self.count_down_votes(restaurant)
  Vote.where(:restaurantID => restaurant, :split => 'f').count
end

  def self.get_user_votes(user_param)
    Vote.joins('LEFT OUTER JOIN restaurants ON restaurants.id = votes.restaurantID').where('votes.user = ?', user_param)
  end

  def self.get_vote_restaurant_name(restaurant)
    Restaurant.where(:id => restaurant).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :except => [:index, :show]

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { go_back }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { go_back }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end 
    end
  end



  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private

  #Redirect_to_back
  def go_back
 
    #Attempt to redirect
    redirect_to :back
 
    #Catch exception and redirect to root
    rescue ActionController::RedirectBackError
      redirect_to root_path
   end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.permit(:comment, :user, :restaurantID, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @favorites = Favorite.all
    respond_with(@favorites)
  end

  def show
    respond_with(@favorite)
  end

  def new
    @favorite = Favorite.new
    respond_with(@favorite)
  end

  def edit
  end

  def create
    @favorite = Favorite.new(favorite_params)
    @favorite.save
    go_back
  end

  def update
    @favorite.update(favorite_params)
    respond_with(@favorite)
  end

  def destroy
    @favorite.destroy
    respond_with(@favorite)
  end

  private

  #Redirect_to_back
  def go_back
 
    #Attempt to redirect
    redirect_to :back
 
    #Catch exception and redirect to root
    rescue ActionController::RedirectBackError
      redirect_to root_path
   end
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    def favorite_params
      params.require(:favorite).permit(:user, :restaurantID)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :increase_up_votes, :increase_down_votes]


  # GET /restaurants
  # GET /restaurants.json
  def index
    if params[:search].present?    
      @restaurants = Restaurant.search params[:search], page: params[:page], per_page: 10
    else
      @restaurants = Restaurant.order("name").page(params[:page]).per(10)
    end
	@comments = Comment.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)


    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant	
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address1, :address2, :city, :state, :zip, :up_votes, :down_votes)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @votes = Vote.all
  end

  def show
  end

  def new
    @vote = Vote.new
  end

  def create
    @vote = Vote.create(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { go_back }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  #Redirect_to_back
  def go_back
 
    #Attempt to redirect
    redirect_to :back
 
    #Catch exception and redirect to root
    rescue ActionController::RedirectBackError
      redirect_to root_path
   end


    def set_vote
      @vote = Vote.find(params[:id])
    end

    def vote_params
      params.require(:vote).permit(:restaurantID, :split, :user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :restaurantID %><br>
    <%= f.number_field :restaurantID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<h1>Listing favorites</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurantid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user %></td>
        <td><%= favorite.restaurantID %></td>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite.user %>
</p>

<p>
  <strong>Restaurantid:</strong>
  <%= @favorite.restaurantID %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Split The Check</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
<div id="banner">
  <h1>Split the Check</h1>
  <h3>Does your favorite restaurant do it?</h3>
</div>

<p>
<% if user_signed_in? %>
  Logged in as <strong><%= link_to current_user.email, user_details_path %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required=>true %>
  </div>
  <div class="field">
    <%= f.label "Address" %><br>
    <%= f.text_field :address1, :required=>true %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, :required=>true %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state, :required=>true %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip, :required=>true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<br>
<div style="text-align:center"><h1>Start by searching for your favorite restaurant!</h2>
<%= form_tag(restaurants_path, method: "get") do %>
  <%= label_tag(:search, "Search for:") %>
  <%= text_field_tag(:search) %>
  <%= submit_tag("Search") %>
<% end %>

</style></div>
 
<h2>Restaurants:</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Will Split</th>
      <th>Won't Split</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>    
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address1 %><br><%= restaurant.address2 %></td>
        <td><%= restaurant.city %></td>
        <td><%= restaurant.state %></td>
        <td><%= restaurant.zip %></td>
	<td><%= Vote.count_up_votes(restaurant.id) %></td>
	<td><%= Vote.count_down_votes(restaurant.id) %></td>
        <td><%= link_to 'Vote', restaurant %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @restaurants %>
<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h2><strong><%= @restaurant.name %></strong></h2>
<p><%= @restaurant.address1 %>
   <% if @restaurant.address2 %>
      <%= @restaurant.address2 %>
   <% end %><br>
   <%= @restaurant.city %>,
   <%= @restaurant.state %>
   <%= @restaurant.zip %>
</p>

<% if Favorite.is_favorite(current_user.email, @restaurant.id) %>
  <div>**This restaurant is marked as one of your favorites!**</div>
<% else %>
  <div><%= button_to "Make Favorite", :controller => "favorites", :action => "create", :favorite => {:user => current_user.email, :restaurantID => @restaurant.id } %></div>
<% end %>

<br>
<div>
  <u><%= Vote.count_up_votes(@restaurant.id) %></u> vote(s) that this restaurant WILL split the check.
</div>
<div>
  <u><%= Vote.count_down_votes(@restaurant.id) %></u> vote(s) that this restaurant WILL NOT split the check.
</div>
<br>

<% if user_signed_in? %> 
<div>Have you asked to split the check at this restaurant? VOTE!</div>
<p>
   <%= button_to "Will Split", :controller => "votes",
	:action => "create", :vote => { :restaurantID => @restaurant.id, :split => 't', :user => current_user.email} %>
   <%= button_to "Won't Split", :controller => "votes",
	:action => "create", :vote => { :restaurantID => @restaurant.id, :split => 'f', :user => current_user.email} %>
<br><br>

Add a comment:<br>
<%= form_tag(:controller => "comments", :action => "create") do %>
 <%= hidden_field_tag :user, current_user.email %>
 <%= hidden_field_tag :restaurantID, @restaurant.id %>
 <%= text_area_tag :body %><br>
 <%= submit_tag("Comment") %>
<% end %> 
</p>
<% else %>
  <div style="font-size: 1.5em">Please sign up or login to vote!</style></div>
<% end %>


<div>Comments:</div>
<% @restaurant.comments.get_comments(@restaurant.id).each do |comment| %>
	<p><%= comment.user %> said... "<%= comment.body %>"</p>
<% end %>

<br>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/user.html.erb
<h2><strong>User Profile</strong></h2>
<div><%= current_user.email %></div><br>

<div>You made the following comments:</div>
<p><% Comment.get_user_comments(current_user.email).each do |comment| %>
	<%= Comment.get_comment_restaurant_name(comment.id).name %>: 
	"<%= comment.body %>"<br>
<% end %>
</p><br>
<div>Your votes:</div>
<p><% Vote.get_user_votes(current_user.email).each do |vote| %>
	<%= Vote.get_vote_restaurant_name(vote.restaurantID).name %>
	<% if vote.split == true %>
	Will Split
	<% else %>
	Won't Split
	<% end %>
<br>
<% end %>
</p><br>	

<div>You selected the following restaurants as favorites:</div>
<% @favorites = Favorite.get_user_favorites(current_user.email) %>
<p><% @favorites.each do |favorite| %>
	<%= favorite.name %><br>
<% end %>
</p><br>
<%= link_to 'Back', restaurants_path %>